import React from 'react';
import { motion } from 'framer-motion';
import { BookOpen } from 'lucide-react';
import styles from './AISummaryCard.module.css';

/**
 * AISummaryCard Component
 * Displays AI-generated summary of the code review
 * Shows key findings and overall assessment
 */
const AISummaryCard = ({ summary = '' }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="w-full p-6 rounded-xl backdrop-blur-md bg-purple-900/20 border border-purple-500/50"
    >
      <div className="flex items-center gap-3 mb-4">
        <BookOpen className="w-5 h-5 text-purple-400" />
        <h3 className="text-lg font-semibold text-white">AI Review Summary</h3>
      </div>

      <div className="prose prose-invert max-w-none">
        <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">{summary}</p>
      </div>

      {/* Confidence indicator */}
      <div className="mt-4 pt-4 border-t border-purple-500/30">
        <p className="text-xs text-purple-300">
          This assessment was generated by AI and should be reviewed by a human developer.
        </p>
      </div>
    </motion.div>
  );
};

export default AISummaryCard;
